{
  "hash": "88fc7ff9dc5798c84d6cd0d3ce3f18db",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Basic skills - a test\"\nformat: html\neditor: visual\nexecute:\n  eval: true\n---\n\n\n\n\n\n\n\n\n## Datacamp\n\nIn the first week, you will have almost two full days to learn the basics of R yourself. We have given you access to [DataCamp](https://datacamp.com/), a great interactive platform to learn R at any level. The courses we would like you to complete because they prepare you with all you need to know to follow the rest of the course are as follows:\n\n- \"Introduction to R\"\n- \"Introduction to tidyverse\"\n- \"Introduction to dplyr\"\n\nPlease follow them at your own speed. If you think something is too easy because you already have some prior experience, you can skip through it and learn at your own speed. Feel free to start other courses too. All we want you to be able to do, is gain the skills and experience to be able to complete the exercises below. These exercises are therefore not graded in any way, it's just a way to make sure you understand the basics to continue with the rest of the course.\n\n::: {.callout-important title=\"A note on AI\"}\nYou can find the answers and code when you click on the toggle, but try to do as much as you can without looking at the answers first. You can also see that you will find the answer and then the code, after clicking on it. This is another way in which you can get a 'hint' - i.e. the answer, to make you think about what kind of code you need to receive such an answer.\n\nYou can use Google or your notes from DataCamp to find the answers, but please don't use ChatGPT or other AI tools to help you find the answers directly. For example, don't just put the question as a prompt, but you could ask: how do I calculate the mean in R? Or: how can I make a basic plot with ggplot2 to visualise XYZ? In other words: don't 'cheat', but if you want to use ChatGPT, use it in a way that will help you learn and it doesn't hand the answer to you.\n:::\n\n### Data description\n\nLet's work with some global height dataset. It was downloaded from the website <https://ncdrisc.org/data-downloads-height.html> and the file can be found in the `data` directory. The data contain the mean heights of adolescents of both boys and girls at different age groups. The mean height is the mean height of a certain age group in a specific year.\n\n### Part 1: exploration\n\n-   The dataset is called `NCD_RisC_Lancet_2020_heigh_child_adolescent_global.csv` and is stored in the `data` directory. What does the `.csv` extension mean?\n\n::: {.callout-tip title=\"Answer\" collapse=true}\n\nCsv stands for comma separated file. It is a file format to store tables (such as Excel files), where each line represents a data record, and fields are separated by commas. CSV files are commonly used to store data, but you have to be careful if your data contains text that might include comma's, because it will think the sentence needs to be split up into different fields! Other ways to separate fields are for example by using tabs (\\t) or spaces.\n\n:::\n\n-   Import the data set and assign it to a variable (called e.g. `data`)\\\n\n::: {.callout-tip title=\"Code and answer\" collapse=true}\n\nWe are working within an R project, so we can use relative path names. If you prefer using the absolute path name, this might look different. Also, path specification is dependent on your operating system. This has been done in iOS (Apple), but Windows looks different.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# using read.csv\ndata <- read.csv(\"../data/NCD_RisC_Lancet_2020_height_child_adolescent_global.csv\")\n\n# or absolute path name\ndata <- read.csv(\"/Users/vistor/Documents/Work/GitHub/postdoc/special_module_molecol_popgen/data/NCD_RisC_Lancet_2020_height_child_adolescent_global.csv\") \n\n# or using read table, make sure you specify there's a header!\ndata <- read.table(\"../data/NCD_RisC_Lancet_2020_height_child_adolescent_global.csv\", sep = \",\", header=T)\n```\n:::\n\n\n\n\n\n\n\n\n:::\n\n-   How many data entries are there?\n\nNumber of data entries = number of rows, because we are dealing with a data table.\n\n::: {.callout-tip title=\"Code and answer\" collapse=true}\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(data) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1050\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nSo 1050 entries =  this excludes the header.\n\n:::\n\n-   What is the youngest age group in the dataset, and what is the oldest age group (i.e. how old are those groups)?\n\n::: {.callout-tip title=\"Code and answer\" collapse=true}\n\nFirst we need to know what columns there are in the data and what they are called, which can be done in different ways.\n\nRemember you can always view the data (by clicking on it in the environment or by calling `View(data`)).\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# this shows you just the structure of the table\nstr(data) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t1050 obs. of  5 variables:\n $ Sex                       : chr  \"Boys\" \"Boys\" \"Boys\" \"Boys\" ...\n $ Year                      : int  1985 1985 1985 1985 1985 1985 1985 1985 1985 1985 ...\n $ Age.group                 : int  5 6 7 8 9 10 11 12 13 14 ...\n $ Mean.height               : chr  \"105.6490519\" \"111.6353523\" \"117.1894908\" \"122.4381031\" ...\n $ Mean.height.standard.error: chr  \"0.258115469\" \"0.227526225\" \"0.210784409\" \"0.199455168\" ...\n```\n\n\n:::\n\n```{.r .cell-code}\n# this tells you the column names of the table\nnames(data) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Sex\"                        \"Year\"                      \n[3] \"Age.group\"                  \"Mean.height\"               \n[5] \"Mean.height.standard.error\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# this shows you the first 6 entries and the column names\nhead(data) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Sex Year Age.group Mean.height Mean.height.standard.error\n1 Boys 1985         5 105.6490519                0.258115469\n2 Boys 1985         6 111.6353523                0.227526225\n3 Boys 1985         7 117.1894908                0.210784409\n4 Boys 1985         8 122.4381031                0.199455168\n5 Boys 1985         9 127.4997942                0.194521726\n6 Boys 1985        10 132.7080987                0.187002286\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nFrom this we can see that the column that stores the age is called `Age.group`\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# minimum age i.e. youngest age class\nmin(data$Age.group) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5\n```\n\n\n:::\n\n```{.r .cell-code}\n# maximum age i.e. oldest age class\nmax(data$Age.group) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 19\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nSo 5 and 19, respectively.\n\n:::\n\n### Part 2: cleaning the data\n\n-   What is the data type / class of the mean height and its standard error?\n\n::: {.callout-tip title=\"Code and answer\" collapse=true}\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# this tells us the class of a specific column\nclass(data$Mean.height) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"character\"\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(data$Mean.height.standard.error) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"character\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# this tells us the class of all columns\nstr(data) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t1050 obs. of  5 variables:\n $ Sex                       : chr  \"Boys\" \"Boys\" \"Boys\" \"Boys\" ...\n $ Year                      : int  1985 1985 1985 1985 1985 1985 1985 1985 1985 1985 ...\n $ Age.group                 : int  5 6 7 8 9 10 11 12 13 14 ...\n $ Mean.height               : chr  \"105.6490519\" \"111.6353523\" \"117.1894908\" \"122.4381031\" ...\n $ Mean.height.standard.error: chr  \"0.258115469\" \"0.227526225\" \"0.210784409\" \"0.199455168\" ...\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nBoth are characters/strings.\n\n:::\n\n-   Hmm, this data class is probably incorrect... It should be numeric, right? What's causing this?\n\n::: {.callout-tip title=\"Code and answer\" collapse=true}\n\nA classic coding issue, \"what's up with my data\"? Figuring out why something is not behaving as expected will happen most of the time you are coding. How do we diagnose the problem?\n\nWe can start by having a look at the data using e.g. `View(data)` and by doing some tests.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# let's see what happens when we change the data class to numeric, and store this in a test variable.\n\ntest <- as.numeric(data$Mean.height)  \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: NAs introduced by coercion\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nIt gives a warning which indicates it could not change one or more of the values to numeric so it had to be put to NA. Why?\n\nWhat sometimes works is to sort the column, this might help us diagnose what is happening in such a large table. When we look at `View(data)` / the data tab, we can click on the column `Mean.height` and it will sort it. Click on it again, and it will sort it in reverse order\n\nWhatever way you used, you might have identified the issue!\n\nThere are two \"ERRORS\" at row number 112, a boy of age class 1992 and age 11. This text is causing the error, as R doesn't recognise this column as numeric now.\n\n:::\n\n-   Fix the error and change the data class to numeric\n\n::: {.callout-tip title=\"Code and answer\" collapse=true}\n\nWe can't correct the value because we don't know what happened with this boy's height measurement. So let's either remove the entire row or change the values to NA. You could do this manually by going into the raw data using e.g. Excel. But a better practise is by doing this in the code - this way we can always track exactly what we did, and others can see it too because it is documented.\n\nIn the first method below, we simply remove the 112'th row, so we remove the entire data point. It's always smart to store something in a different variable if you remove something so you do not override the original data, I'm showing you an example here but we'll continue with the 'data' variable as we know it's all good. \n\nIn the second and third method, we remove the text \"ERROR\" and instead replace it with the 'official' NA value that R recognises as NA. \n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## method 1\n# remove the row\ndata_clean <- data[-112,] \n\n# then we change the data class to numeric and we do not get a warning\ndata_clean$Mean.height <- as.numeric(data_clean$Mean.height) \n# same for the SE\ndata_clean$Mean.height.standard.error <- as.numeric(data_clean$Mean.height.standard.error) \n\n## method 2\n# this is what we had done before and automatically put the 'character' ERROR as NA, you'll get a warning but now we know why\n\ndata$Mean.height <- as.numeric(data$Mean.height) \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: NAs introduced by coercion\n```\n\n\n:::\n\n```{.r .cell-code}\n# same for the SE\ndata$Mean.height.standard.error <- as.numeric(data$Mean.height.standard.error) \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: NAs introduced by coercion\n```\n\n\n:::\n\n```{.r .cell-code}\n## method 3\n\n# this is the same as above, but manually which is a bit longer and more complex\n\ndata$Mean.height[which(data$Mean.height==\"ERROR\")] <- NA \ndata$Mean.height.standard.error[which(data$Mean.height.standard.error==\"ERROR\")] <- NA \n\n# change to numeric, now we won't get a warning\ndata$Mean.height <- as.numeric(data$Mean.height) \ndata$Mean.height.standard.error <- as.numeric(data$Mean.height.standard.error) \n```\n:::\n\n\n\n\n\n\n\n\nThere we go! It's always good to check if things worked, so you can use e.g. `str(data)` now to check that R indeed changed the columns to numeric.\n\n:::\n\n### Part 3: summary statistics\n\n-   What is the mean across years of the mean heights in the dataset?\n\n::: {.callout-tip title=\"Code and answer\" collapse=true}\n\nThe function that calculates means is, intuitively, `mean()` which is a base function (i.e. you don't need to install a package for this). If you want to know more details about how to use a function, you can use `?mean`\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# we have to make sure we remove the NA when calculating the mean though!\nmean(data$Mean.height, na.rm = T) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 141.7635\n```\n\n\n:::\n\n```{.r .cell-code}\n# or we use the data that doesn't contain the NA\nmean(data_clean$Mean.height) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 141.7635\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n:::\n-   What is the mean across years of the mean height, calculated separately for boys and girls?\n\n::: {.callout-tip title=\"Code and answer\" collapse=true}\n\nHere's where your preference can kick in: do you want to use dplyr or something else, like base R or data.table? I will show you multiple options, just see what looks more intuitive to you. To make sure we can use dplyr, we have to load the library.\n\nTo answer this question, we have to do multiple steps: divide the data among the sexes somehow, and calculate the mean. This can be done in steps, or in one go. If you're a computational scientists, you would want things to be done in as little code as possible. But since we are learning, just do what makes most sense to you.\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# method 1 with dplyr\nlibrary(dplyr) # we can use dplyr to use the filter option\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code}\ngirls <- data %>% filter(Sex == \"Girls\")\nboys <- data %>% filter(Sex == \"Boys\")\n\nmean(girls$Mean.height, na.rm = T) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 140.02\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(boys$Mean.height, na.rm = T) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 143.5103\n```\n\n\n:::\n\n```{.r .cell-code}\n# method 2 without dplyr\nmean(data$Mean.height[which(data$Sex == \"Girls\")], na.rm=T) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 140.02\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(data$Mean.height[which(data$Sex == \"Boys\")], na.rm=T) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 143.5103\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n:::\n-   In what year was the standard error lowest for boys and girls separately, for the age class 12? (i.e. the variance smallest?)\n\nAgain, we need to take multiple steps here: only look at data from the Age group 12, and then look at what year the variance was the smallest (i.e. the minimal variance).\n\nI'll only show you the dplyr way, but you can use many different methods to get to the same answer here.\n\n::: {.callout-tip title=\"Code and answer\" collapse=true}\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# method 1: with dplyr\ngirls_12yr <- girls %>% filter(Age.group == 12)\nboys_12yr <- boys %>% filter(Age.group == 12)\n\ngirls_12yr %>% arrange(Mean.height.standard.error) %>% head() # 2003, with a SE of 0.09367336\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Sex Year Age.group Mean.height Mean.height.standard.error\n1 Girls 2003        12    146.6524                 0.09367336\n2 Girls 2004        12    146.7459                 0.09369505\n3 Girls 2005        12    146.8387                 0.09382388\n4 Girls 2002        12    146.5615                 0.09397351\n5 Girls 2006        12    146.9259                 0.09423025\n6 Girls 2001        12    146.4734                 0.09451832\n```\n\n\n:::\n\n```{.r .cell-code}\nboys_12yr %>% arrange(Mean.height.standard.error) %>% head() # 2004, with a SE of 0.1342430\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Sex Year Age.group Mean.height Mean.height.standard.error\n1 Boys 2004        12    144.8178                  0.1342430\n2 Boys 2003        12    144.7568                  0.1343755\n3 Boys 2005        12    144.8627                  0.1347293\n4 Boys 2002        12    144.6810                  0.1349744\n5 Boys 2006        12    144.8881                  0.1355101\n6 Boys 2001        12    144.5841                  0.1360441\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n:::\n\n### Part 4: plotting\n\n-   Make a plot that shows you whether the mean height of 18 year olds increased or decreased over time. Bonus if you do it seperately per sex!\n\n::: {.callout-tip title=\"Code and answer\" collapse=true}\n\nLet's get plotting! First choose: do you want to use ggplot2 (recommended) or base R to make your plot?\n\nBefore you start making code, think what elements should be on the axes. What should be on the X axis, what variable on the Y axis, and what type of graph would represent the data best? A boxplot, scatterplot, line graph, pie chart? Choose the right element accordingly and then start writing the code. \n\nWe also have to use a portion of the data only, again. We can use dplyr (`filter()`) but I will also show you another function here, `subset()` which is a base R function to do something similar to `filter()`.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# method 1: with ggplot\nlibrary(ggplot2)\n\nggplot(subset(data, Age.group == 18), aes(x = Year, y = Mean.height)) + geom_point(aes(col = Sex)) + geom_line(aes(col = Sex)) + theme_classic()\n```\n\n::: {.cell-output-display}\n![](test_introduction_files/figure-html/exercise 11-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# method 2: base R -- not sure how to do it\n```\n:::\n\n\n\n\n\n\n\n\n\nAs we see, both the mean height of girls and boys aged 18 years increased over time. What is also clear is that base R is a lot longer, and you require a lot of separate elements.\n\n:::\n\n\n\nWell done! If you managed to answer all of the above, with or without some help from your notes and the internet, you're ready to explore genetic data and answer some pop gen questions.",
    "supporting": [
      "test_introduction_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}